In [1]:
import numpy as np
import pandas as pd
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [16]:
df = pd.read_csv("/Datasets/PCA.csv")
df

X1  X2  X3  x4  X5  X6
0   2   3   4   5   6   7
1   1   5   3   6   7   8

In [17]:
 mean = pd.DataFrame(df.mean(axis=1), columns = ["Mean"])
mean

Mean
0   4.5
1   5.0

In [18]:
df = df.sub(mean["Mean"], axis = 0)
new=df.T
new

0    1
X1 -2.5 -4.0
X2 -1.5  0.0
X3 -0.5 -2.0
x4  0.5  1.0
X5  1.5  2.0
X6  2.5  3.0

In [19]:
conv = np.cov(df)
length = len(df.T)
new = conv*((length-1)/length)
new

array([[2.91666667, 3.66666667],
       [3.66666667, 5.66666667]])

In [10]:
char_eqn = np.poly(new)
char_eqn

array([ 1.        , -8.58333333,  3.08333333])

In [11]:
from numpy.linalg import eig


In [20]:
eigval, eigvec = eig(new)
print("Hence the principal components are: ", eigval[0], eigval[1])
print(eigvec)

Hence the principal components are:  0.37566495006279865 8.207668383270537
[[-0.82192562 -0.56959484]
 [ 0.56959484 -0.82192562]]


In [41]:
X = np.linalg.inv(new)
print(X)
ans = X.dot(eigval)
ans

[[ 1.83783784 -1.18918919]
 [-1.18918919  0.94594595]]


array([-9.07005925,  7.31727394])